---
netunicorn.infrastructure.connectors:
  defaultdocker:
    enabled: true
    module: "netunicorn.director.infrastructure.connectors"  # where to import from
    class: "DockerConnector"  # class name
    config: "/app/infrastructure-example-config.yaml"     # path to configuration file

netunicorn.infrastructure.connectors.docker.base_url: "unix://var/run/docker.sock"
netunicorn.infrastructure.providers.docker.default_network: "netunicorn-network"