version: "3.9"

x-common-variables: &common-variables
  NETUNICORN_LOG_LEVEL: "DEBUG"
  NETUNICORN_DATABASE_ENDPOINT: "postgres"
  NETUNICORN_DATABASE_DB: "development"
  NETUNICORN_DATABASE_USER: "development"
  NETUNICORN_DATABASE_PASSWORD: "development"
  NETUNICORN_GATEWAY_ENDPOINT: "http://localhost:26612"


services:
  registry:
    container_name: netunicorn-dev-registry
    image: registry:2
    restart: unless-stopped
    ports:
      - "0.0.0.0:5000:5000"

  postgres:
    container_name: netunicorn-dev-database
    image: postgres
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: development
      POSTGRES_DB: development
    restart: unless-stopped
    volumes:
      - ./scripts/dbdeploy.sql:/docker-entrypoint-initdb.d/0_dbdeploy.sql
      - ./scripts/dev-users.sql:/docker-entrypoint-initdb.d/1_dev_users.sql

  authentication:
    build: ./netunicorn-authentication
    # image: netunicorn/authentication:latest
    container_name: netunicorn-dev-authentication
    restart: unless-stopped
    environment:
      <<: *common-variables
      NETUNICORN_AUTHENTICATION_IP: "0.0.0.0"

  compilation:
    build: ./netunicorn-compilation
    # image: netunicorn/compilation:latest
    container_name: netunicorn-dev-compilation
    restart: always
    environment: *common-variables
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  gateway:
    build: ./netunicorn-gateway
    # image: netunicorn/gateway:latest
    container_name: netunicorn-dev-gateway
    restart: always
    environment:
      <<: *common-variables
      NETUNICORN_GATEWAY_IP: "0.0.0.0"
    ports:
      - "0.0.0.0:26612:26512"

  processor:
    build: ./netunicorn-processor
    # image: netunicorn/processor:latest
    container_name: netunicorn-dev-processor
    restart: always
    environment: *common-variables

  infrastructure:
    build: ./netunicorn-infrastructure
    # image: netunicorn/infrastructure:latest
    container_name: netunicorn-example-infrastructure
    restart: always
    command: -f infrastructure-example-config.yaml
    environment:
      <<: *common-variables
      NETUNICORN_INFRASTRUCTURE_IP: "0.0.0.0"
    volumes:
      - ./scripts/infrastructure-example-config.yaml:/app/infrastructure-example-config.yaml
      - /var/run/docker.sock:/var/run/docker.sock

  mediator:
    build: ./netunicorn-mediator
    # image: netunicorn/mediator:latest
    container_name: netunicorn-dev-mediator
    restart: always
    environment:
      <<: *common-variables
      NETUNICORN_MEDIATOR_IP: "0.0.0.0"
      NETUNICORN_MEDIATOR_PORT: "26511"
      NETUNICORN_INFRASTRUCTURE_ENDPOINT: "http://infrastructure:26514"
      NETUNICORN_AUTH_ENDPOINT: "http://authentication:26516"
      NETUNICORN_DOCKER_REGISTRY_URL: "localhost:5000"
    ports:
      - "0.0.0.0:26611:26511"
    depends_on:
      - authentication
      - gateway
      - processor
      - infrastructure
      - compilation
      - postgres
      - registry
