version: "3.9"

x-common-variables: &common-variables
  NETUNICORN_LOG_LEVEL: "DEBUG"
  NETUNICORN_DATABASE_ENDPOINT: "database:5432"
  NETUNICORN_DATABASE_DB: "unicorndb"
  # of course, better use .env file for this
  NETUNICORN_DATABASE_USER: "some_user"
  NETUNICORN_DATABASE_PASSWORD: "some_password"

x-common-variable: &gateway-variables
  NETUNICORN_GATEWAY_IP: "some.public.dns.or.ip"
  NETUNICORN_GATEWAY_PORT: "26512"


# currently you need to manually run netunicorn-compilation to build the images

services:
  database:
    image: postgres:13
    container_name: netunicorn-database
    restart: always
    environment:
      POSTGRES_USER: ${NETUNICORN_DATABASE_USER}
      POSTGRES_PASSWORD: ${NETUNICORN_DATABASE_PASSWORD}
      POSTGRES_DB: ${NETUNICORN_DATABASE_DB}
    volumes:
      - ./data:/var/lib/postgresql/data

  authentication:
    image: netunicorn/authentication:latest
    container_name: netunicorn-authentication
    restart: always
    environment: *common-variables
    depends_on:
      - database
    ports:
      - "26516:26516"

  gateway:
    image: netunicorn/gateway:latest
    container_name: netunicorn-gateway
    restart: always
    environment:
        <<: *common-variables
        <<: *gateway-variables
    ports:
      - "${NETUNICORN_GATEWAY_IP}:${NETUNICORN_GATEWAY_PORT}:${NETUNICORN_GATEWAY_PORT}"
    depends_on:
      - database

  processor:
    image: netunicorn/processor:latest
    container_name: netunicorn-processor
    restart: always
    environment: *common-variables
    depends_on:
      - database

  infrastructure:
    image: netunicorn/infrastructure:latest
    container_name: netunicorn-infrastructure
    restart: always
    environment: *common-variables
    depends_on:
      - database

  mediator:
    image: netunicorn/mediator:latest
    container_name: netunicorn-mediator
    restart: always
    environment:
      <<: *common-variables
      <<: *gateway-variables
      NETUNICORN_MEDIATOR_IP: "127.0.0.1"
      NETUNICORN_MEDIATOR_PORT: "26511"
      NETUNICORN_INFRASTRUCTURE_ENDPOINT: "http://infrastructure:26511"
      NETUNICORN_AUTH_ENDPOINT: "http://authentication:26516"
      NETUNICORN_DOCKER_REGISTRY_URL: "custom.registry.com"
    ports:
      - "${NETUNICORN_MEDIATOR_IP}:${NETUNICORN_MEDIATOR_PORT}:${NETUNICORN_MEDIATOR_PORT}"
    depends_on:
      - database
      - authentication
      - gateway
      - processor
      - infrastructure
