version: "3.9"

x-common-variables: &common-variables
  NETUNICORN_LOG_LEVEL: "DEBUG"
  NETUNICORN_DATABASE_ENDPOINT: "netunicorn.example.com/database"
  NETUNICORN_DATABASE_DB: "somedb"
  NETUNICORN_DATABASE_USER: "dbuser"
  NETUNICORN_DATABASE_PASSWORD: "dbpassword"

x-common-variable: &gateway-variables
    NETUNICORN_GATEWAY_ENDPOINT: "https://netunicorn.example.com/gateway"


services:
  authentication:
    image: netunicorn/authentication:latest
    container_name: netunicorn-authentication
    restart: always
    environment:
      <<: *common-variables
      NETUNICORN_AUTHENTICATION_IP: "0.0.0.0"

  compilation:
    image: netunicorn/compilation:latest
    container_name: netunicorn-compilation
    restart: always
    environment: *common-variables
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  gateway:
    image: netunicorn/gateway:latest
    container_name: netunicorn-gateway
    restart: always
    environment:
        <<: *common-variables
        NETUNICORN_GATEWAY_IP: "0.0.0.0"
    ports:
      - "127.0.0.1:26512:26512"

  processor:
    image: netunicorn/processor:latest
    container_name: netunicorn-processor
    restart: always
    environment: *common-variables

  infrastructure:
    image: netunicorn/infrastructure:latest
    container_name: netunicorn-infrastructure
    restart: always
    command: -f infrastructure-config.yaml
    environment:
      <<: *common-variables
      <<: *gateway-variables
      NETUNICORN_INFRASTRUCTURE_IP: "0.0.0.0"
    volumes:
      - /srv/netunicorn/infrastructure-config.yaml:/app/infrastructure-config.yaml  # MODIFY THIS


  mediator:
    image: netunicorn/mediator:latest
    container_name: netunicorn-mediator
    restart: always
    environment:
      <<: *common-variables
      <<: *gateway-variables
      NETUNICORN_MEDIATOR_IP: "0.0.0.0"
      NETUNICORN_MEDIATOR_PORT: "26511"
      NETUNICORN_INFRASTRUCTURE_ENDPOINT: "http://infrastructure:26514"
      NETUNICORN_AUTH_ENDPOINT: "http://authentication:26516"
      NETUNICORN_DOCKER_REGISTRY_URL: "netunicorn.registry.example.com"
      PROXY_PATH: "/netunicorn"
    ports:
      - "127.0.0.1:26511:26511"
    depends_on:
      - authentication
      - gateway
      - processor
      - infrastructure
      - compilation
