# run me with a context of main netunicorn directory!
version: "3.9"

x-common-variables: &common-variables
  NETUNICORN_LOG_LEVEL: "DEBUG"
  NETUNICORN_DATABASE_ENDPOINT: "postgres"
  NETUNICORN_DATABASE_DB: "development"
  NETUNICORN_DATABASE_USER: "development"
  NETUNICORN_DATABASE_PASSWORD: "development"
  NETUNICORN_GATEWAY_ENDPOINT: "http://localhost:26612"


services:
  registry:
    container_name: netunicorn-dev-registry
    image: registry:2
    restart: unless-stopped
    ports:
      - "0.0.0.0:5000:5000"

  postgres:
    container_name: netunicorn-dev-database
    image: postgres
    environment:
      POSTGRES_USER: development
      POSTGRES_PASSWORD: development
      POSTGRES_DB: development
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/dbdeploy.sql:/docker-entrypoint-initdb.d/0_dbdeploy.sql
      - ./scripts/dev-users.sql:/docker-entrypoint-initdb.d/1_dev_users.sql

  authentication:
    image: netunicorn-dev-image
    command: -m netunicorn.director.authentication
    build:
        context: ..
        dockerfile: ./netunicorn-director/scripts/dev.Dockerfile
    container_name: netunicorn-dev-authentication
    restart: unless-stopped
    environment:
      <<: *common-variables
      NETUNICORN_AUTHENTICATION_IP: "0.0.0.0"
    depends_on:
      - postgres

  compilation:
    image: netunicorn-dev-image
    command: -m netunicorn.director.compilation
    container_name: netunicorn-dev-compilation
    restart: always
    environment: *common-variables
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - postgres

  gateway:
    image: netunicorn-dev-image
    command: -m netunicorn.director.gateway
    container_name: netunicorn-dev-gateway
    restart: always
    environment:
      <<: *common-variables
      NETUNICORN_GATEWAY_IP: "0.0.0.0"
    ports:
      - "0.0.0.0:26612:26512"
    depends_on:
      - postgres

  processor:
    image: netunicorn-dev-image
    command: -m netunicorn.director.processor
    container_name: netunicorn-dev-processor
    restart: always
    environment: *common-variables
    depends_on:
      - postgres

  infrastructure:
    image: netunicorn-dev-image
    command: -m netunicorn.director.infrastructure -f /app/infrastructure-example-config.yaml
    container_name: netunicorn-example-infrastructure
    restart: always
    depends_on:
      - postgres
    environment:
      <<: *common-variables
      NETUNICORN_INFRASTRUCTURE_IP: "0.0.0.0"
    volumes:
      - ./scripts/infrastructure-example-config.yaml:/app/infrastructure-example-config.yaml
      - /var/run/docker.sock:/var/run/docker.sock

  mediator:
    image: netunicorn-dev-image
    command: -m netunicorn.director.mediator
    container_name: netunicorn-dev-mediator
    restart: always
    environment:
      <<: *common-variables
      NETUNICORN_MEDIATOR_IP: "0.0.0.0"
      NETUNICORN_MEDIATOR_PORT: "26511"
      NETUNICORN_INFRASTRUCTURE_ENDPOINT: "http://infrastructure:26514"
      NETUNICORN_AUTH_ENDPOINT: "http://authentication:26516"
      NETUNICORN_DOCKER_REGISTRY_URL: "localhost:5000"
    ports:
      - "0.0.0.0:26611:26511"
    depends_on:
      - authentication
      - gateway
      - processor
      - infrastructure
      - compilation
      - postgres
      - registry
