events { }

http {
    server {
        listen 80;
        server_name localhost;

        # Proxy requests to the React application
        location / {
            proxy_pass http://ui-new:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            # Handle client-side routing for React
            # try_files $uri $uri/ /index.html;
        }

        # Proxy requests to the API
        location /api/ {
            proxy_pass http://mediator:26511/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_connect_timeout 600s;
            proxy_send_timeout 600s;
            proxy_read_timeout 600s;

            add_header 'Access-Control-Allow-Origin' '*';
            add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS';
            add_header 'Access-Control-Allow-Headers' 'Origin, Content-Type, Accept, Authorization';
            if ($request_method = OPTIONS) {
                return 204;
            }
        }
    }
}

