name: netunicorn-gateway codechecks

on:
  pull_request:
    branches: [ "main", "develop" ]
  paths:
    - "netunicorn-gateway/**"

jobs:
  codechecks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pylint mypy isort

      - name: Run Black
        run: black --check --diff ./netunicorn-gateway

      - name: Run isort
        run: isort --profile black --check --diff ./netunicorn-gateway

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run MyPy on netunicorn-gateway
        uses: jpetrucciani/mypy-check@master
        with:
          path: './netunicorn-gateway'
          mypy_flags: '--config-file ./netunicorn-gateway/pyproject.toml'
          requirements_file: './misc/requirements.dev.txt'
