name: netunicorn-infrastructure codechecks

on:
  pull_request:
    branches: [ "main", "develop" ]
  paths:
    - "netunicorn-infrastructure/**"

jobs:
  codechecks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pylint mypy isort

      - name: Run Black
        run: black --check --diff ./netunicorn-infrastructure

      - name: Run isort
        run: isort --profile black --check --diff ./netunicorn-infrastructure

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run MyPy on netunicorn-infrastructure
        uses: jpetrucciani/mypy-check@master
        with:
          path: './netunicorn-infrastructure'
          mypy_flags: '--config-file ./netunicorn-infrastructure/pyproject.toml'
          requirements_file: './misc/requirements.dev.txt'
