# This workflow will build a netunicorn-director-mediator Docker image and push it to Docker Hub

name: Release netunicorn-director-mediator

on:
  push:
    paths:
      - "netunicorn-director/netunicorn-mediator/pyproject.toml"
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: netunicorn-director/netunicorn-mediator
        push: true
        tags: netunicorn/mediator:latest
