name: netunicorn-client codechecks

on:
  pull_request:
    branches: [ "main", "develop" ]
    paths:
      - "netunicorn-client/**"

jobs:
  codechecks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black pylint mypy isort

      - name: Run Black
        run: black --check --diff ./netunicorn-client

      - name: Run isort
        run: isort --profile black --check --diff ./netunicorn-client

      - name: Run MyPy on netunicorn-client
        uses: jpetrucciani/mypy-check@master
        with:
          path: './netunicorn-client'
          mypy_flags: '--config-file ./netunicorn-client/pyproject.toml'
          requirements_file: './misc/requirements.dev.txt'
